import type { AffiliateZone } from "@/lib/types"

export const AFFILIATE_SEED_DATA: Array<{
  zone: AffiliateZone; zone_label: string; name: string
  shopee_url: string | null; lazada_url: string | null
}> = [
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "ปลอกหมอนอิง", shopee_url: "https://s.shopee.co.th/3foBvGzzq0", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "สติ๊กเกอร์ติดสวิตซ์ไฟ", shopee_url: "https://s.shopee.co.th/8UtRgBPBnF", lazada_url: "https://c.lazada.co.th/t/c.YXkolZ" },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "เครื่องฟอกอากาศ Levoit Core 600S", shopee_url: "https://s.shopee.co.th/BEJktcEQz", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "ชั้นวางกาแฟดำติดผนัง", shopee_url: "https://s.shopee.co.th/60C3Tmafl2", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "รูปภาพแต่งแนว MCM", shopee_url: "https://s.shopee.co.th/qTxKOHLzn", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "ชั้นวางแก้ว IKEA", shopee_url: "https://s.shopee.co.th/5KwMgWDYF0", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "ที่กดน้ำ 4L", shopee_url: "https://s.shopee.co.th/2qF1hhEpyF", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "เครื่องชงกาแฟ ทำลาเต้อาร์ตได้", shopee_url: "https://s.shopee.co.th/utcbD0fg", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "เครื่องบด Modern เล็กแต่แรง", shopee_url: "https://s.shopee.co.th/2AzKuXlFFG", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "กระจกนูนกลม (ร้านนี้ราคาดีที่ตามหามานาน)", shopee_url: "https://s.shopee.co.th/Vr6v6ekDZ", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "หมอนกลม Muji", shopee_url: "https://s.shopee.co.th/5fZD4iDEHO", lazada_url: "https://c.lazada.co.th/t/c.YXkolG" },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "โคมไฟเห็ดสีส้ม", shopee_url: "https://s.shopee.co.th/3VZ95BQPO2", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "พัดลมเล็ก MCM", shopee_url: "https://s.shopee.co.th/uqN7GybB", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "Barcelona Chair สีน้ำตาล", shopee_url: "https://s.shopee.co.th/9f5LtHsYcH", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "สติ๊กเกอร์ลายไม้มีเท็กเจอร์ ติดเฟอร์นิเจอร์", shopee_url: "https://s.shopee.co.th/60C6jLGarg", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "สติ๊กเกอร์ลายไม้มีเท็กเจอร์ ติดผนัง (น้ำตาล)", shopee_url: "https://s.shopee.co.th/LXk0aaqP2", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "เก้าอี้ไม้สีน้ำเงิน IKEA", shopee_url: "https://s.shopee.co.th/4fgj9FUaUC", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "เก้าอี้โค้งพลาสติกสีเหลือง", shopee_url: "https://s.shopee.co.th/8pWI8AR4qH", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "ตาชั่งกาแฟ Timemore", shopee_url: "https://s.shopee.co.th/9f5P7rX43H", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "ที่รองแก้วน้ำ Burger", shopee_url: "https://s.shopee.co.th/5KwRUQrxE9", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "ที่เกลี่ยกาแฟ ไม่ให้เป็นก้อน", shopee_url: "https://s.shopee.co.th/8pWJf7Pqf1", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "แท่นวางก้านชง", shopee_url: "https://s.shopee.co.th/2AzPiyh2Q5", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "แก้วเก็บความเย็น การ์ตูนเขียว", shopee_url: "https://s.shopee.co.th/60C8ICBlTS", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "กระถางต้นไม้ เก็บน้ำ", shopee_url: "https://s.shopee.co.th/8pWJfYEScE", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "ขาแขวนทีวี ติดผนัง", shopee_url: "https://s.shopee.co.th/VrBoClWgD", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "โคมไฟเห็ด เหลือง", shopee_url: "https://s.shopee.co.th/9UnLPu9RBI", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "ชั้นวาง Stacko", shopee_url: "https://s.shopee.co.th/2LMdwbzKFc", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "โปสเตอร์ MCM", shopee_url: "https://s.shopee.co.th/6pp2yFWsRs", lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "https://s.shopee.co.th/7ASCv8WcXF", shopee_url: null, lazada_url: null },
  { zone: "living_room", zone_label: "ห้องรับแขก", name: "กระจก Disco", shopee_url: "https://s.shopee.co.th/2LN4wx4Bnj", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ไฟเซ็นเซอร์  LED เปลี่ยนได้ 3 สี", shopee_url: "https://s.shopee.co.th/2VcEVHg5lh", lazada_url: "https://s.lazada.co.th/s.GSnKJ?cc" },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ชั้นวางปรับระดับได้", shopee_url: "https://s.shopee.co.th/3foBtT5dn0", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ไม้พายซิลิโคน หลากสี", shopee_url: "https://s.shopee.co.th/7fKKeqtf3Q", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ตะขอแขวน pegboard", shopee_url: "https://s.shopee.co.th/5psgSskvTc", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ที่รองหม้อ รองของร้อนแบบเชือกถัก", shopee_url: "https://s.shopee.co.th/2qF4tOe98C", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ตะกร้าเคลือบสีขาวมีรูระบายน้ำ", shopee_url: "https://s.shopee.co.th/10nQi41dqP", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ที่แขวนกระดาษทิชชูในห้องครัว", shopee_url: "https://s.shopee.co.th/5VFq4N1AFp", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ชั้นเก็บจานชานพร้อมรางเลื่อน", shopee_url: "https://s.shopee.co.th/2VcEUtGvtR", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "กรรไกรครัวถอดล้างได้", shopee_url: "https://s.shopee.co.th/6fRnSZQimI", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ราวแขวนพร้อมตะขอไม่ต้องเจาะ", shopee_url: "https://s.shopee.co.th/1VjhJ6JK0C", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "โหลถนอมอาหารสูญญากาศ", shopee_url: "https://s.shopee.co.th/10nQiCxryA", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ขวดใส่น้ำมัน เทได้ สเปรย์ได้", shopee_url: "https://s.shopee.co.th/utWPRCHx", lazada_url: "https://c.lazada.co.th/t/c.YXkoSt" },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ป้ายชื่อสายไฟ", shopee_url: "https://s.shopee.co.th/3VUlhEHaFV", lazada_url: "https://c.lazada.co.th/t/c.YXko7i" },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ชั้นวางใต้ซิงค์ปรับยืดหดได้", shopee_url: "https://s.shopee.co.th/4AkSUX9FFX", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ขวดใส่เครื่องปรุง", shopee_url: "https://s.shopee.co.th/40R2IFvK3F", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "สติ๊ิกเกอร์ติดเครื่องปรุง", shopee_url: "https://s.shopee.co.th/2AzO6uWUPz", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ถังขยะแขวนเคาเตอร์", shopee_url: "https://s.shopee.co.th/4VNItERCNP", lazada_url: "https://c.lazada.co.th/t/c.YXkoij" },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ที่วางฟองน้ำล้างจานแบบสแตนเลส", shopee_url: "https://s.shopee.co.th/4L3shkBdDP", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "พรมพื้นห้องครัว PU กันน้ำ", shopee_url: "https://s.shopee.co.th/3LBLVzMlgX", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "กระทะสีเหลือง locknlock", shopee_url: "https://s.shopee.co.th/AA1febLSXp", lazada_url: "https://c.lazada.co.th/t/c.YXkno2" },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "เครื่องกรองน้ำดื่ม Yomizu", shopee_url: "https://s.shopee.co.th/40R2JKUo9V", lazada_url: "https://s.lazada.co.th/s.GS4Ff?cc" },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "หัวต่อก๊อกน้ำปรับหมุนได้รอบทิศทาง", shopee_url: "https://s.shopee.co.th/2VcEWdPl8j", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ถังใส่ข้าวสาร", shopee_url: "https://s.shopee.co.th/AUeW3Mcgty", lazada_url: "https://c.lazada.co.th/t/c.YXPu9I" },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "Pegboard แขวนกระทะ", shopee_url: "https://s.shopee.co.th/3VUiXRK9zj", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "แม่เหล็กติดตู้เย็น รูปอาหาร น่ารัก หลายแบบ", shopee_url: "https://s.shopee.co.th/3LBLYMtMxt", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ที่หนีบถุงขนม ลายเฟรนส์ฟราย  มีแม่เหล็กติดตู้เย็น", shopee_url: "https://s.shopee.co.th/2qF4xyv0KU", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "กล่องแก้วสูญญากาศ Neoflam", shopee_url: null, lazada_url: "https://c.lazada.co.th/t/c.YXknQI" },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "กล่องเก็บอาหาร Locknlock", shopee_url: null, lazada_url: "https://c.lazada.co.th/t/c.YXknnb" },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "พัดลมเล็ก Muji", shopee_url: null, lazada_url: "https://c.lazada.co.th/t/c.YXPujY" },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "ตะแกรงวางหม้อ วางของร้อน", shopee_url: "https://s.shopee.co.th/1qQSBu9Ve3", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "เครื่องบดพริกไทย เกลือ", shopee_url: null, lazada_url: "https://s.lazada.co.th/s.yOsfu?cc" },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "เครื่องดูดควัน", shopee_url: "https://s.shopee.co.th/6AZxJatabT", lazada_url: null },
  { zone: "kitchen", zone_label: "ห้องครัว", name: "เตาแก๊ส", shopee_url: "https://s.shopee.co.th/7fOl6N6RtA", lazada_url: null },
  { zone: "bathroom", zone_label: "ห้องน้ำ", name: "ชั้นวางไดร์เป่าผม", shopee_url: "https://s.shopee.co.th/1VjhLqKyeW", lazada_url: null },
  { zone: "bathroom", zone_label: "ห้องน้ำ", name: "ไดร์เป่าผมไอออน ผมแห้งไว ไม่ชี้ฟู", shopee_url: "https://s.shopee.co.th/VrAA2ItBg", lazada_url: "https://c.lazada.co.th/t/c.YXkoLp" },
  { zone: "bathroom", zone_label: "ห้องน้ำ", name: "แปรงขัดโถส้วมมีที่เก็บ", shopee_url: "https://s.shopee.co.th/6AVWuTofhu", lazada_url: null },
  { zone: "bathroom", zone_label: "ห้องน้ำ", name: "ชั้นวางของสีขาวมีล้อ เก็บของในที่แคบ", shopee_url: "https://s.shopee.co.th/6fRnVQpflM", lazada_url: null },
  { zone: "bathroom", zone_label: "ห้องน้ำ", name: "ถังขยะอัตโนมัติแบบสแตนเลส เปิดปิดสมูทมาก", shopee_url: "https://s.shopee.co.th/9A98U3kITy", lazada_url: "https://c.lazada.co.th/t/c.YXkoT6" },
  { zone: "bathroom", zone_label: "ห้องน้ำ", name: "ไฟดาวน์ไลท์ LED ขาว", shopee_url: "https://s.shopee.co.th/705ZU1yrtl", lazada_url: null },
  { zone: "bathroom", zone_label: "ห้องน้ำ", name: "กระจกยืด IKEA FRACK (กลม)", shopee_url: "https://s.shopee.co.th/10pdp5SSod", lazada_url: null },
  { zone: "miscellaneous", zone_label: "ของใช้เบ็ดเตล็ด", name: "Digital door lock  สามารถใช้สแกนลายนิ้วมือ คีย์การ์ด กดรหัส กุญแจ แอปพลิเคชั่น", shopee_url: "https://s.shopee.co.th/7pdktn6JFI", lazada_url: "https://c.lazada.co.th/t/c.YXko67" },
  { zone: "miscellaneous", zone_label: "ของใช้เบ็ดเตล็ด", name: "เตาแก๊สปิคนิคมินิมูจิ", shopee_url: "https://c.lazada.co.th/t/c.YXkn6h", lazada_url: null },
  { zone: "miscellaneous", zone_label: "ของใช้เบ็ดเตล็ด", name: "กระเป๋าใส่เตาแก๊สปิคนิคมินิมูจิ", shopee_url: "https://c.lazada.co.th/t/c.YXknTD", lazada_url: null },
  { zone: "miscellaneous", zone_label: "ของใช้เบ็ดเตล็ด", name: "มูจิเตาแก๊สปิคนิคสีขาว", shopee_url: "https://c.lazada.co.th/t/c.YXknit", lazada_url: null },
  { zone: "miscellaneous", zone_label: "ของใช้เบ็ดเตล็ด", name: "ที่แขวนโต๊ะรีดผ้า", shopee_url: "https://s.shopee.co.th/AKL5selatU", lazada_url: null },
  { zone: "miscellaneous", zone_label: "ของใช้เบ็ดเตล็ด", name: "ที่แขวนอุปกรณ์ทำความสะอาดติดผนังแบบสแตนเลส", shopee_url: "https://s.shopee.co.th/6Kox7H2BCE", lazada_url: null },
  { zone: "miscellaneous", zone_label: "ของใช้เบ็ดเตล็ด", name: "หัวม๊อปถูพื้นมูจิ", shopee_url: "https://s.lazada.co.th/s.GS4je?cc", lazada_url: null },
  { zone: "miscellaneous", zone_label: "ของใช้เบ็ดเตล็ด", name: "ผ้าม๊อปถูพื้นมูจิ", shopee_url: "https://s.lazada.co.th/s.GSeuK?cc", lazada_url: null },
  { zone: "miscellaneous", zone_label: "ของใช้เบ็ดเตล็ด", name: "หัวแปรงขัดห้องน้ำมูจิ", shopee_url: "https://s.lazada.co.th/s.GSfiE?cc", lazada_url: null },
  { zone: "miscellaneous", zone_label: "ของใช้เบ็ดเตล็ด", name: "ที่รีดน้ำกระจกมูจิ", shopee_url: "https://s.lazada.co.th/s.GSfmb?cc", lazada_url: null },
  { zone: "miscellaneous", zone_label: "ของใช้เบ็ดเตล็ด", name: "กล้องวงจรปิด IMILAB EC6 ชัดมาก คุยตอบโต้ได้ หมุนได้รอบทิศทาง เชื่อมต่อแอป Mi Home", shopee_url: "https://s.shopee.co.th/AA1fgeJRsQ", lazada_url: "https://c.lazada.co.th/t/c.YXknmS" },
  { zone: "miscellaneous", zone_label: "ของใช้เบ็ดเตล็ด", name: "เก้าอี้พลาสติก แข็งแรง ดีไซน์สวย", shopee_url: "https://s.shopee.co.th/8AGbJ9ZTTl", lazada_url: null },
  { zone: "miscellaneous", zone_label: "ของใช้เบ็ดเตล็ด", name: "พรมดักฝุ่นรูปหน้ายิ้มสีเหลือง", shopee_url: "https://s.shopee.co.th/7V0uWM0IMF", lazada_url: null },
  { zone: "miscellaneous", zone_label: "ของใช้เบ็ดเตล็ด", name: "แปรงสีฟันไฟฟ้า Oral-B  โปร 2", shopee_url: "https://c.lazada.co.th/t/c.YXkn8e", lazada_url: null },
  { zone: "miscellaneous", zone_label: "ของใช้เบ็ดเตล็ด", name: "ไฟโซล่าเซลล์ Randy", shopee_url: "https://c.lazada.co.th/t/c.YXkn8w", lazada_url: null },
  { zone: "miscellaneous", zone_label: "ของใช้เบ็ดเตล็ด", name: "ถังขยะสแตนเลสแบบเหยียบปิดนุ่มนวล Hafele", shopee_url: "https://s.lazada.co.th/s.GS4y6?cc", lazada_url: null },
  { zone: "miscellaneous", zone_label: "ของใช้เบ็ดเตล็ด", name: "แก้วมัคสแตนเลสเก็บอุณหภูมิ LocknLock", shopee_url: "https://c.lazada.co.th/t/c.YXknnv", lazada_url: null },
  { zone: "appliances", zone_label: "เครื่องใช้ไฟฟ้า", name: "Levoit Core 600S Air Purifier", shopee_url: "https://s.shopee.co.th/1Vjmz1QXp4", lazada_url: "https://c.lazada.co.th/t/c.YXkNqG" },
  { zone: "appliances", zone_label: "เครื่องใช้ไฟฟ้า", name: "Xiaomi Smart Air Purifier 4 Compact", shopee_url: "https://s.shopee.co.th/8AGgvgHX8K", lazada_url: "https://c.lazada.co.th/t/c.YXkngF" },
  { zone: "appliances", zone_label: "เครื่องใช้ไฟฟ้า", name: "Xiaomi Smart Air Purifier 4 Lite", shopee_url: "https://s.shopee.co.th/uzClOXpt", lazada_url: "https://c.lazada.co.th/t/c.YXkn5v" },
  { zone: "appliances", zone_label: "เครื่องใช้ไฟฟ้า", name: "เครื่องซักผ้า อบผ้า LG Wash Tower", shopee_url: "https://s.lazada.co.th/s.GtsJL?cc", lazada_url: "https://s.lazada.co.th/s.GtsF1?cc" },
  { zone: "appliances", zone_label: "เครื่องใช้ไฟฟ้า", name: "เครื่ื่องดูดฝุ่น Tineco Pure One Station 5", shopee_url: null, lazada_url: null },
  { zone: "appliances", zone_label: "เครื่องใช้ไฟฟ้า", name: "MOVA X4 Pro", shopee_url: "https://s.shopee.co.th/4q4fbPivYK", lazada_url: null },
  { zone: "appliances", zone_label: "เครื่องใช้ไฟฟ้า", name: "กล้องวงจรปิด C22", shopee_url: null, lazada_url: null },
  { zone: "appliances", zone_label: "เครื่องใช้ไฟฟ้า", name: "พัดลมเพดาน", shopee_url: null, lazada_url: null },
  { zone: "appliances", zone_label: "เครื่องใช้ไฟฟ้า", name: "เครื่องกรองน้ำ กดน้ำร้อน philips", shopee_url: "https://s.shopee.co.th/8V3OfQzw0B", lazada_url: null },
  { zone: "garden", zone_label: "สวนนอกบ้าน", name: "ม้านั่งสนาม แดง", shopee_url: "https://s.shopee.co.th/6pmfA3upFZ", lazada_url: null },
  { zone: "garden", zone_label: "สวนนอกบ้าน", name: "เก้าอี้พลาสติก (เหลือง)", shopee_url: "https://s.shopee.co.th/2qJkzjWakW", lazada_url: null },
  { zone: "garden", zone_label: "สวนนอกบ้าน", name: "กล้องวงจร EC6 Panorma 180•", shopee_url: "https://s.shopee.co.th/4VOd771gw6", lazada_url: null },
  { zone: "garden", zone_label: "สวนนอกบ้าน", name: "แผ่นปูวัชพืช Geotextile", shopee_url: "https://s.shopee.co.th/9zmHeqb9Ms", lazada_url: null },
  { zone: "garden", zone_label: "สวนนอกบ้าน", name: "ไฟรั้ว โซลาร์เซลล์ SL Lighting", shopee_url: "https://s.shopee.co.th/3qC2TLxhb9", lazada_url: null },
  { zone: "garden", zone_label: "สวนนอกบ้าน", name: "ไฟโซลาร์เซลล์ 300w เหลี่ยม", shopee_url: "https://s.shopee.co.th/40VltIQtzK", lazada_url: null },
  { zone: "garden", zone_label: "สวนนอกบ้าน", name: "กล้องวงจรปิด C40  ชัด 4K", shopee_url: "https://s.shopee.co.th/6Aj6G2M5pf", lazada_url: null },
  { zone: "workspace", zone_label: "โต๊ะทำงาน+Gadget", name: "Top โต๊ะ", shopee_url: null, lazada_url: null },
  { zone: "workspace", zone_label: "โต๊ะทำงาน+Gadget", name: "โคมไฟกระดาษกลม", shopee_url: null, lazada_url: null },
  { zone: "workspace", zone_label: "โต๊ะทำงาน+Gadget", name: "ไมค์ Fifine k688", shopee_url: null, lazada_url: null },
  { zone: "workspace", zone_label: "โต๊ะทำงาน+Gadget", name: "หูฟัง Edifier", shopee_url: null, lazada_url: null },
  { zone: "workspace", zone_label: "โต๊ะทำงาน+Gadget", name: "Smart Plug", shopee_url: "https://s.shopee.co.th/1g6wrZhFGl", lazada_url: null },
  { zone: "workspace", zone_label: "โต๊ะทำงาน+Gadget", name: "Keychron V5 Max", shopee_url: "https://s.shopee.co.th/6VN3TmTLCC", lazada_url: null },
  { zone: "wall_shelf", zone_label: "ชั้นวาง ผนัง", name: "รางรับชั้น Stacko (ขาว)", shopee_url: "https://s.shopee.co.th/2LMdwbzKFc", lazada_url: null },
  { zone: "wall_shelf", zone_label: "ชั้นวาง ผนัง", name: "แผ่นไม้ Stacko (ขาว)", shopee_url: "https://s.shopee.co.th/BI9MpFVsv", lazada_url: null },
  { zone: "wall_shelf", zone_label: "ชั้นวาง ผนัง", name: "แขนรับชั้น Stacko (ขาว)", shopee_url: "https://s.shopee.co.th/8010hHIVer", lazada_url: null },
  { zone: "wall_shelf", zone_label: "ชั้นวาง ผนัง", name: "รางรับชั้น Stacko (ดำ)", shopee_url: "https://s.shopee.co.th/7KlWffmCtI", lazada_url: null },
  { zone: "wall_shelf", zone_label: "ชั้นวาง ผนัง", name: "แผ่นไม้ Stacko (ดำ)", shopee_url: null, lazada_url: null },
  { zone: "wall_shelf", zone_label: "ชั้นวาง ผนัง", name: "แขนรับชั้น Stacko (ดำ)", shopee_url: "https://s.shopee.co.th/1Vnjj2AWEs", lazada_url: null },
]
